import { readFile, writeFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';

const root = new URL('../', import.meta.url);
const [css, compatibilityCss, runtime, icon, pkg] = await Promise.all([
  readFile(new URL('src/skin.css', root), 'utf8'),
  readFile(new URL('src/compatibility.css', root), 'utf8'),
  readFile(new URL('src/runtime.js', root), 'utf8'),
  readFile(new URL('codex-plus-plus/spider-gwen-icon.png', root)),
  readFile(new URL('package.json', root), 'utf8').then(JSON.parse),
]);
const signature = createHash('sha256').update([pkg.version, css, compatibilityCss, runtime].map(value => value.replace(/\r\n/g, '\n')).join('\0')).digest('hex');
const result = `// Generated by scripts/build.mjs; edit src/skin.css, src/compatibility.css and src/runtime.js.\n(() => {\n  const VERSION = ${JSON.stringify(pkg.version)};\n  const SOURCE_SIGNATURE = ${JSON.stringify(signature)};\n  const CSS = ${JSON.stringify(css.replace(/\r\n/g, '\n'))};\n  const COMPATIBILITY_CSS = ${JSON.stringify(compatibilityCss.replace(/\r\n/g, '\n'))};\n  const ICON_DATA_URL = ${JSON.stringify(`data:image/png;base64,${icon.toString('base64')}`)};\n${runtime.replace(/\r\n/g, '\n').trimEnd()}\n})();\n`;
const output = new URL('codex-plus-plus/spider-gwen-immersive.js', root);
if (process.argv.includes('--check')) {
  if ((await readFile(output, 'utf8')).replace(/\r\n/g, '\n') !== result) throw new Error('Bundle is stale. Run node scripts/build.mjs.');
  console.log('Bundle matches source.');
} else {
  await writeFile(output, result);
  console.log(`Built Spider-Gwen ${pkg.version}.`);
}
